
//! This module holds the [Protocol Buffers](https://developers.google.com/protocol-buffers/)
//! structs, generated by [rust-protobuf](https://github.com/stepancheg/rust-protobuf).

#[allow(unused_qualifications, deprecated, missing_docs)]
mod secret;
pub use self::secret::{RustySecret, RustySecretsVersions};

#[allow(unused_qualifications, deprecated, missing_docs)]
 mod share_data;
pub use self::share_data::ShareData;
